BTCPayServer/Models/ServerViewModels/EmailsViewModel.cs
using System.ComponentModel.DataAnnotations;
using BTCPayServer.Services.Mails;

namespace BTCPayServer.Models.ServerViewModels
{
    public class EmailsViewModel
    {
        public EmailsViewModel()
        {

        }
        public EmailsViewModel(EmailSettings settings)
        {
            Settings = settings;
            PasswordSet = !string.IsNullOrEmpty(settings?.Password);
        }
        public EmailSettings Settings
        {
            get; set;
        }
        public bool PasswordSet { get; set; }
        [EmailAddress]
        [Display(Name = "Test Email")]
        public string TestEmail
        {
            get; set;
        }
    }
}

BTCPayServer/Models/StoreViewModels/CheckoutAppearanceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using BTCPayServer.Payments;
using BTCPayServer.Services;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BTCPayServer.Models.StoreViewModels
{
    public class CheckoutAppearanceViewModel
    {
        public class Format
        {
            public string Name { get; set; }
            public string Value { get; set; }
            public PaymentMethodId PaymentId { get; set; }
        }
        public SelectList PaymentMethods { get; set; }

        public void SetLanguages(LanguageService langService, string defaultLang)
        {
            defaultLang = langService.GetLanguages().Any(language => language.Code == defaultLang) ? defaultLang : "en";
            var choices = langService.GetLanguages().Select(o => new Format() { Name = o.DisplayName, Value = o.Code }).ToArray().OrderBy(o => o.Name);
            var chosen = choices.FirstOrDefault(f => f.Value == defaultLang) ?? choices.FirstOrDefault();
            Languages = new SelectList(choices, nameof(chosen.Value), nameof(chosen.Name), chosen);
            DefaultLang = chosen.Value;
        }
        public SelectList Languages { get; set; }

        [Display(Name = "Default payment method on checkout")]
        public string DefaultPaymentMethod { get; set; }

        [Display(Name = "Requires a refund email")]
        public bool RequiresRefundEmail { get; set; }

        [Display(Name = "Only enable the payment method after user explicitly chooses it")]
        public bool LazyPaymentMethods { get; set; }

        [Display(Name = "Redirect invoice to redirect url automatically after paid")]
        public bool RedirectAutomatically { get; set; }

        [Display(Name = "Auto-detect language on checkout")]
        public bool AutoDetectLanguage { get; set; }

        [Display(Name = "Default language on checkout")]
        public string DefaultLang { get; set; }

        [Display(Name = "Link to a custom CSS stylesheet")]
        public string CustomCSS { get; set; }
        [Display(Name = "Link to a custom logo")]
        public string CustomLogo { get; set; }

        [Display(Name = "Custom HTML title to display on Checkout page")]
        public string HtmlTitle { get; set; }

        public List<PaymentMethodCriteriaViewModel> PaymentMethodCriteria { get; set; }
    }

    public class PaymentMethodCriteriaViewModel
    {
        public string PaymentMethod { get; set; }
        public string Value { get; set; }

        public CriteriaType Type { get; set; }

        public enum CriteriaType
        {
            GreaterThan,
            LessThan
        }
        public static string ToString(CriteriaType type)
        {
            switch (type)
            {
                case CriteriaType.GreaterThan:
                    return "Greater than";
                case CriteriaType.LessThan:
                    return "Less than";
                default:
                    throw new ArgumentOutOfRangeException(nameof(type), type, null);
            }
        }

    }
}

BTCPayServer/Models/StoreViewModels/GeneralSettingsViewModel.cs
using System.ComponentModel.DataAnnotations;
using BTCPayServer.Client.Models;
using BTCPayServer.Validation;

namespace BTCPayServer.Models.StoreViewModels
{
    public class GeneralSettingsViewModel
    {

        [Display(Name = "Store ID")]
        public string Id { get; set; }

        [Display(Name = "Store Name")]
        [Required]
        [MaxLength(50)]
        [MinLength(1)]
        public string StoreName { get; set; }

        [Uri]
        [Display(Name = "Store Website")]
        [MaxLength(500)]
        public string StoreWebsite { get; set; }

        public bool CanDelete { get; set; }

        [Display(Name = "Allow anyone to create invoice")]
        public bool AnyoneCanCreateInvoice { get; set; }

        [Display(Name = "Invoice expires if the full amount has not been paid after …")]
        [Range(1, 60 * 24 * 24)]
        public int InvoiceExpiration { get; set; }

        [Display(Name = "Add additional fee (network fee) to invoice …")]
        public NetworkFeeMode NetworkFeeMode { get; set; }

        [Display(Name = "Consider the invoice paid even if the paid amount is ... % less than expected")]
        [Range(0, 100)]
        public double PaymentTolerance { get; set; }

        [Display(Name = "Default currency")]
        [MaxLength(10)]
        public string DefaultCurrency { get; set; }

        [Display(Name = "Minimum acceptable expiration time for BOLT11 for refunds")]
        [Range(1, 365 * 10)]
        public long BOLT11Expiration { get; set; }
    }
}

BTCPayServer/Models/StoreViewModels/IntegrationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static BTCPayServer.Data.StoreBlob;

namespace BTCPayServer.Models.StoreViewModels
{
    public class IntegrationsViewModel
    {
    }
}

BTCPayServer/Models/StoreViewModels/LightningSettingsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BTCPayServer.Models.StoreViewModels
{
    public class LightningSettingsViewModel : LightningNodeViewModel
    {
        // Payment
        [Display(Name = "Display Lightning payment amounts in Satoshis")]
        public bool LightningAmountInSatoshi { get; set; }

        [Display(Name = "Add hop hints for private channels to the Lightning invoice")]
        public bool LightningPrivateRouteHints { get; set; }

        [Display(Name = "Include Lightning invoice fallback to on-chain BIP21 payment URL")]
        public bool OnChainWithLnInvoiceFallback { get; set; }

        [Display(Name = "Description template of the lightning invoice")]
        public string LightningDescriptionTemplate { get; set; }

        // LNURL
        [Display(Name = "Enable LNURL")]
        public bool LNURLEnabled { get; set; }

        [Display(Name = "LNURL Classic Mode")]
        public bool LNURLBech32Mode { get; set; } = true;

        [Display(Name = "LNURL enabled for standard invoices")]
        public bool LNURLStandardInvoiceEnabled { get; set; } = true;

        [Display(Name = "Allow payee to pass a comment")]
        public bool LUD12Enabled { get; set; }

        [Display(Name = "Do not offer BOLT11 for standard invoices")]
        public bool DisableBolt11PaymentMethod { get; set; }
    }
}

BTCPayServer/Models/StoreViewModels/LightningViewModel.cs
using System.Collections.Generic;

namespace BTCPayServer.Models.StoreViewModels;

public class LightningViewModel : LightningNodeViewModel
{
    public List<AdditionalServiceViewModel> Services { get; set; }
}

BTCPayServer/Models/StoreViewModels/TestWebhookViewModel.cs
using BTCPayServer.Client.Models;

namespace BTCPayServer.Models.StoreViewModels
{
    public class TestWebhookViewModel
    {
        public WebhookEventType Type { get; set; }
    }
}

BTCPayServer/Controllers/UIStoresController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Client;
using BTCPayServer.Configuration;
using BTCPayServer.Data;
using BTCPayServer.HostedServices;
using BTCPayServer.Models;
using BTCPayServer.Models.StoreViewModels;
using BTCPayServer.Payments;
using BTCPayServer.Payments.Lightning;
using BTCPayServer.Rating;
using BTCPayServer.Security.Bitpay;
using BTCPayServer.Services;
using BTCPayServer.Services.Apps;
using BTCPayServer.Services.Invoices;
using BTCPayServer.Services.Rates;
using BTCPayServer.Services.Stores;
using BTCPayServer.Services.Wallets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using NBitcoin;
using NBitcoin.DataEncoders;
using StoreData = BTCPayServer.Data.StoreData;

namespace BTCPayServer.Controllers
{
    [Route("stores")]
    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie)]
    [Authorize(Policy = Policies.CanModifyStoreSettings, AuthenticationSchemes = AuthenticationSchemes.Cookie)]
    [AutoValidateAntiforgeryToken]
    public partial class UIStoresController : Controller
    {
        public UIStoresController(
            IServiceProvider serviceProvider,
            BTCPayServerOptions btcpayServerOptions,
            BTCPayServerEnvironment btcpayEnv,
            StoreRepository repo,
            TokenRepository tokenRepo,
            UserManager<ApplicationUser> userManager,
            BitpayAccessTokenController tokenController,
            BTCPayWalletProvider walletProvider,
            BTCPayNetworkProvider networkProvider,
            RateFetcher rateFactory,
            ExplorerClientProvider explorerProvider,
            LanguageService langService,
            PaymentMethodHandlerDictionary paymentMethodHandlerDictionary,
            SettingsRepository settingsRepository,
            IAuthorizationService authorizationService,
            EventAggregator eventAggregator,
            AppService appService,
            WebhookSender webhookNotificationManager,
            IDataProtectionProvider dataProtector,
            NBXplorerDashboard Dashboard,
            IOptions<ExternalServicesOptions> externalServiceOptions)
        {
            _RateFactory = rateFactory;
            _Repo = repo;
            _TokenRepository = tokenRepo;
            _UserManager = userManager;
            _LangService = langService;
            _TokenController = tokenController;
            _WalletProvider = walletProvider;
            _paymentMethodHandlerDictionary = paymentMethodHandlerDictionary;
            _settingsRepository = settingsRepository;
            _authorizationService = authorizationService;
            _appService = appService;
            DataProtector = dataProtector.CreateProtector("ConfigProtector");
            WebhookNotificationManager = webhookNotificationManager;
            _EventAggregator = eventAggregator;
            _NetworkProvider = networkProvider;
            _ExplorerProvider = explorerProvider;
            _ServiceProvider = serviceProvider;
            _BtcpayServerOptions = btcpayServerOptions;
            _BTCPayEnv = btcpayEnv;
            _Dashboard = Dashboard;
            _externalServiceOptions = externalServiceOptions;
        }

        readonly BTCPayServerOptions _BtcpayServerOptions;
        readonly BTCPayServerEnvironment _BTCPayEnv;
        readonly IServiceProvider _ServiceProvider;
        readonly BTCPayNetworkProvider _NetworkProvider;
        readonly BTCPayWalletProvider _WalletProvider;
        readonly BitpayAccessTokenController _TokenController;
        readonly StoreRepository _Repo;
        readonly TokenRepository _TokenRepository;
        readonly UserManager<ApplicationUser> _UserManager;
        readonly RateFetcher _RateFactory;
        private readonly ExplorerClientProvider _ExplorerProvider;
        private readonly LanguageService _LangService;
        private readonly PaymentMethodHandlerDictionary _paymentMethodHandlerDictionary;
        private readonly SettingsRepository _settingsRepository;
        private readonly IAuthorizationService _authorizationService;
        private readonly AppService _appService;
        private readonly EventAggregator _EventAggregator;
        private readonly NBXplorerDashboard _Dashboard;
        private readonly IOptions<ExternalServicesOptions> _externalServiceOptions;

        [TempData]
        public bool StoreNotConfigured
        {
            get; set;
        }

        [HttpGet]
        [Route("{storeId}/users")]
        public async Task<IActionResult> StoreUsers()
        {
            StoreUsersViewModel vm = new StoreUsersViewModel();
            await FillUsers(vm);
            return View(vm);
        }

        private async Task FillUsers(StoreUsersViewModel vm)
        {
            var users = await _Repo.GetStoreUsers(CurrentStore.Id);
            vm.StoreId = CurrentStore.Id;
            vm.Users = users.Select(u => new StoreUsersViewModel.StoreUserViewModel()
            {
                Email = u.Email,
                Id = u.Id,
                Role = u.Role
            }).ToList();
        }

        public StoreData CurrentStore
        {
            get
            {
                return this.HttpContext.GetStoreData();
            }
        }
        
        [HttpGet("{storeId}")]
        public IActionResult Dashboard()
        {
            var store = CurrentStore;
            var storeBlob = store.GetStoreBlob();

            AddPaymentMethods(store, storeBlob,
                out var derivationSchemes, out var lightningNodes);
            
            var vm = new StoreDashboardViewModel
            {
                WalletEnabled = derivationSchemes.Any(scheme => !string.IsNullOrEmpty(scheme.Value) && scheme.Enabled),
                LightningEnabled = lightningNodes.Any(ln => !string.IsNullOrEmpty(ln.Address) && ln.Enabled),
                StoreId = CurrentStore.Id,
                StoreName = CurrentStore.StoreName
            };
            
            return View("Dashboard", vm);
        }

        [HttpPost]
        [Route("{storeId}/users")]
        public async Task<IActionResult> StoreUsers(StoreUsersViewModel vm)
        {
            await FillUsers(vm);
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            var user = await _UserManager.FindByEmailAsync(vm.Email);
            if (user == null)
            {
                ModelState.AddModelError(nameof(vm.Email), "User not found");
                return View(vm);
            }
            if (!StoreRoles.AllRoles.Contains(vm.Role))
            {
                ModelState.AddModelError(nameof(vm.Role), "Invalid role");
                return View(vm);
            }
            if (!await _Repo.AddStoreUser(CurrentStore.Id, user.Id, vm.Role))
            {
                ModelState.AddModelError(nameof(vm.Email), "The user already has access to this store");
                return View(vm);
            }
            TempData[WellKnownTempData.SuccessMessage] = "User added successfully.";
            return RedirectToAction(nameof(StoreUsers));
        }

        [HttpGet("{storeId}/users/{userId}/delete")]
        public async Task<IActionResult> DeleteStoreUser(string userId)
        {
            var user = await _UserManager.FindByIdAsync(userId);
            if (user == null)
                return NotFound();
            return View("Confirm", new ConfirmModel("Remove store user", $"This action will prevent <strong>{user.Email}</strong> from accessing this store and its settings. Are you sure?", "Remove"));
        }

        [HttpPost("{storeId}/users/{userId}/delete")]
        public async Task<IActionResult> DeleteStoreUserPost(string storeId, string userId)
        {
            if(await _Repo.RemoveStoreUser(storeId, userId))
                TempData[WellKnownTempData.SuccessMessage] = "User removed successfully.";
            else
            {
                TempData[WellKnownTempData.ErrorMessage] = "Removing this user would result in the store having no owner.";
            }
            return RedirectToAction(nameof(StoreUsers), new { storeId, userId });
        }

        [HttpGet("{storeId}/rates")]
        public IActionResult Rates()
        {
            var exchanges = GetSupportedExchanges();
            var storeBlob = CurrentStore.GetStoreBlob();
            var vm = new RatesViewModel();
            vm.SetExchangeRates(exchanges, storeBlob.PreferredExchange ?? CoinGeckoRateProvider.CoinGeckoName);
            vm.Spread = (double)(storeBlob.Spread * 100m);
            vm.StoreId = CurrentStore.Id;
            vm.Script = storeBlob.GetRateRules(_NetworkProvider).ToString();
            vm.DefaultScript = storeBlob.GetDefaultRateRules(_NetworkProvider).ToString();
            vm.AvailableExchanges = exchanges;
            vm.DefaultCurrencyPairs = storeBlob.GetDefaultCurrencyPairString();
            vm.ShowScripting = storeBlob.RateScripting;
            return View(vm);
        }

        [HttpPost("{storeId}/rates")]
        public async Task<IActionResult> Rates(RatesViewModel model, string command = null, string storeId = null, CancellationToken cancellationToken = default)
        {
            if (command == "scripting-on")
            {
                return RedirectToAction(nameof(ShowRateRules), new { scripting = true, storeId = model.StoreId });
            }
            else if (command == "scripting-off")
            {
                return RedirectToAction(nameof(ShowRateRules), new { scripting = false, storeId = model.StoreId });
            }

            var exchanges = GetSupportedExchanges();

BTCPayServer/Views/UIStores/Dashboard.cshtml
@model StoreDashboardViewModel;

@inject BTCPayNetworkProvider networkProvider
@{
	ViewData.SetActivePage(StoreNavPages.Dashboard, Model.StoreName, Model.StoreId);
	var isReady = Model.WalletEnabled || Model.LightningEnabled;
	var defaultCryptoCode = networkProvider.DefaultNetwork.CryptoCode;
}

<partial name="_StatusMessage" />

<h2 class="mt-1 mb-3">@ViewData["Title"]</h2>

@if (isReady)
{
    <p class="lead text-secondary">This store is ready to accept transactions, good job!</p>
}
else
{
    <p class="lead text-secondary">To start accepting payments, set up a wallet or a Lightning node.</p>
}

<div class="list-group" id="SetupGuide">
    <div class="list-group-item d-flex align-items-center" id="SetupGuide-StoreDone">
        <vc:icon symbol="done"/>
        <div class="content">
            <h5 class="mb-0 text-success">Create your store</h5>
        </div>
    </div>
    @if (!Model.WalletEnabled)
    {
        <a asp-controller="UIStores" asp-action="SetupWallet" asp-route-storeId="@Model.StoreId" asp-route-cryptoCode="@defaultCryptoCode" id="SetupGuide-Wallet" class="list-group-item list-group-item-action d-flex align-items-center order-1">
            <vc:icon symbol="new-wallet"/>
            <div class="content">
                <h5 class="mb-0">Set up a wallet</h5>
            </div>
            <vc:icon symbol="caret-right"/>
        </a>
    }
    else
    {
        <div class="list-group-item d-flex align-items-center" id="SetupGuide-WalletDone">
            <vc:icon symbol="done"/>
            <div class="content">
                <h5 class="mb-0 text-success">Set up a wallet</h5>
            </div>
        </div>
    }
    @if (!Model.LightningEnabled)
    {
        <a asp-controller="UIStores" asp-action="SetupLightningNode" asp-route-storeId="@Model.StoreId" asp-route-cryptoCode="@defaultCryptoCode" id="SetupGuide-Lightning" class="list-group-item list-group-item-action d-flex align-items-center order-1">
            <vc:icon symbol="new-wallet"/>
            <div class="content">
                <h5 class="mb-0">Set up a Lightning node</h5>
            </div>
            <vc:icon symbol="caret-right"/>
        </a>
    }
    else
    {
        <div class="list-group-item d-flex align-items-center" id="SetupGuide-LightningDone">
            <vc:icon symbol="done"/>
            <div class="content">
                <h5 class="mb-0 text-success">Set up a Lightning node</h5>
            </div>
        </div>
    }
</div>

BTCPayServer/Views/UIStores/GenerateWallet.cshtml
@model WalletSetupViewModel
@addTagHelper *, BundlerMinifier.TagHelpers
@{
    var isHotWallet = Model.Method == WalletSetupMethod.HotWallet;
    var type = isHotWallet ? "Hot" : "Watch-Only";
    Layout = "_LayoutWalletSetup";
    ViewData.SetActivePage(StoreNavPages.OnchainSettings, $"Create {Model.CryptoCode} {type} Wallet", Context.GetStoreData().Id);
    ViewData.Add(nameof(Model.CanUseHotWallet), Model.CanUseHotWallet);
    ViewData.Add(nameof(Model.CanUseRPCImport), Model.CanUseRPCImport);
    ViewData.Add(nameof(Model.SupportSegwit), Model.SupportSegwit);
    ViewData.Add(nameof(Model.SupportTaproot), Model.SupportTaproot);
    ViewData.Add(nameof(Model.Method), Model.Method);
}

@section Navbar {
    <a asp-controller="UIStores" asp-action="GenerateWallet" asp-route-storeId="@Model.StoreId" asp-route-cryptoCode="@Model.CryptoCode" asp-route-method="">
        <vc:icon symbol="back" />
    </a>
}

<h1 class="text-center">@ViewData["Title"]</h1>
<br>
<partial name="_GenerateWalletForm" model="Model.SetupRequest" />

@section PageFootContent {
    <partial name="_ValidationScriptsPartial" />
}

BTCPayServer/Views/UIStores/ImportWalletOptions.cshtml
@model WalletSetupViewModel
@inject BTCPayNetworkProvider BTCPayNetworkProvider
@addTagHelper *, BundlerMinifier.TagHelpers
@{
    Layout = "_LayoutWalletSetup";
    ViewData.SetActivePage(StoreNavPages.OnchainSettings, $"Import {Model.CryptoCode} Wallet", Context.GetStoreData().Id);
}

@section Navbar {
    <a asp-controller="UIStores" asp-action="SetupWallet" asp-route-storeId="@Model.StoreId" asp-route-cryptoCode="@Model.CryptoCode">
        <vc:icon symbol="back" />
    </a>
}

<header class="text-center">
    <h1>Choose your import method</h1>
    <p class="lead text-secondary mt-3">The following methods assume that you already have an existing&nbsp;wallet created and backed up.</p>
</header>

@if (BTCPayNetworkProvider.GetNetwork<BTCPayNetwork>(Model.CryptoCode).VaultSupported)
{
    <div class="mt-5">
        <div class="list-group">
            <a asp-controller="UIStores" asp-action="ImportWallet" asp-route-storeId="@Model.StoreId" asp-route-cryptoCode="@Model.CryptoCode" asp-route-method="hardware" id="ImportHardwareLink" class="list-group-item list-group-item-action only-for-js">
                <div class="image">
                    <vc:icon symbol="hardware-wallet"/>
                </div>
                <div class="content d-flex flex-column flex-lg-row align-items-lg-center justify-content-lg-between me-2">
                    <div>
                        <h4>Connect hardware&nbsp;wallet</h4>
                        <p class="mb-0 text-secondary">Import your public keys using our Vault application</p>
                    </div>
                    <small class="d-block text-primary mt-2 mt-lg-0">Recommended</small>
                </div>
                <vc:icon symbol="caret-right" />
            </a>
            <noscript>
                <div class="list-group-item disabled">
                    <div class="image">
                        <vc:icon symbol="hardware-wallet"/>
                    </div>
                    <div class="content d-flex flex-column flex-lg-row align-items-lg-center justify-content-lg-between me-2">
                        <div>
                            <h4>Connect hardware&nbsp;wallet</h4>
                            <p class="mb-0">Please enable JavaScript for this option to be available</p>
                        </div>
                        <small class="d-block text-primary mt-2 mt-lg-0">Recommended</small>
                    </div>
                </div>
            </noscript>
        </div>
    </div>
}

<div class="list-group mt-4">
    <a asp-controller="UIStores" asp-action="ImportWallet" asp-route-storeId="@Model.StoreId" asp-route-cryptoCode="@Model.CryptoCode" asp-route-method="file" id="ImportFileLink" class="list-group-item list-group-item-action">
        <div class="image">
            <vc:icon symbol="wallet-file"/>
        </div>
        <div class="content d-flex flex-column flex-lg-row align-items-lg-center justify-content-lg-between me-2">
            <div>
                <h4>Import wallet file</h4>
                <p class="mb-0 text-secondary">Upload a file exported from your wallet</p>
            </div>
            <small class="d-block text-primary mt-2 mt-lg-0">Recommended</small>
        </div>
        <vc:icon symbol="caret-right" />
    </a>
</div>

<div class="list-group mt-4">
    <a asp-controller="UIStores" asp-action="ImportWallet" asp-route-storeId="@Model.StoreId" asp-route-cryptoCode="@Model.CryptoCode" asp-route-method="xpub" id="ImportXpubLink" class="list-group-item list-group-item-action">
        <div class="image">
            <vc:icon symbol="xpub"/>
        </div>
        <div class="content">
            <h4>Enter extended public key</h4>
            <p class="mb-0 text-secondary">Input the key string manually</p>
        </div>
        <vc:icon symbol="caret-right" />
    </a>
</div>

<div class="list-group mt-4">
    <a asp-controller="UIStores" asp-action="ImportWallet" asp-route-storeId="@Model.StoreId" asp-route-cryptoCode="@Model.CryptoCode" asp-route-method="scan" id="ImportScanLink" class="list-group-item list-group-item-action only-for-js">
        <div class="image">
            <vc:icon symbol="scan-qr"/>
        </div>
        <div class="content">
            <h4>Scan wallet QR code</h4>
            <p class="mb-0 text-secondary">Supported by BlueWallet, Cobo Vault, Passport and Specter DIY</p>
        </div>
        <vc:icon symbol="caret-right" />
    </a>
    <noscript>
        <div class="list-group-item list-group-item-action disabled hide-when-js">
            <div class="image">
                <vc:icon symbol="scan-qr"/>
            </div>
            <div class="content">
                <h4>Scan wallet QR code</h4>
                <p class="mb-0">Please enable JavaScript for this option to be available</p>
            </div>
        </div>
    </noscript>
</div>

<div class="list-group mt-4">
    <a asp-controller="UIStores" asp-action="ImportWallet" asp-route-storeId="@Model.StoreId" asp-route-cryptoCode="@Model.CryptoCode" asp-route-method="seed" id="ImportSeedLink" class="list-group-item list-group-item-action">
        <div class="image">
            <vc:icon symbol="seed"/>
        </div>
        <div class="content d-flex flex-column flex-lg-row align-items-lg-center justify-content-lg-between me-2">
            <div>
                <h4>Enter wallet seed</h4>
                <p class="mb-0 text-secondary">Provide the 12 or 24 word recovery seed</p>
            </div>
            <small class="d-block text-danger mt-2 mt-lg-0" data-bs-toggle="tooltip" data-bs-placement="top" title="You really should not type your seed into a device that is connected to the internet.">Not recommended <span class="fa fa-question-circle-o"></span></small>
        </div>
        <vc:icon symbol="caret-right" />
    </a>
</div>

BTCPayServer/Views/UIStores/RequestPairing.cshtml
@model PairingModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData.SetActivePage(StoreNavPages.Tokens, "Pairing Permission", Context.GetStoreData()?.Id);
}

<h3 class="mb-0">@ViewData["Title"]</h3>
<div class="row">
    <div class="col-md-4">
        <table class="table table-hover removetopborder">
            <tr>
                <th>Label</th>
                <td class="text-end">@Model.Label</td>
            </tr>
            <tr>
                <th>SIN</th>
                <td class="text-end">@Model.SIN</td>
            </tr>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Pair" method="post">
            <div class="form-group">
                <label asp-for="StoreId" class="form-label">Pair To Store</label>
                <select asp-for="StoreId" asp-items="@(new SelectList(Model.Stores,"Id","Name"))" class="form-select"></select>
                <span asp-validation-for="StoreId" class="text-danger"></span>
            </div>
            <input type="hidden" name="pairingCode" value="@Model.Id" />
            <button id="ApprovePairing" type="submit" class="btn btn-primary mt-3" title="Approve this pairing demand">Approve</button>
        </form>
    </div>
</div>

BTCPayServer/Views/UIStores/ShowToken.cshtml
@model BTCPayServer.Security.Bitpay.BitTokenEntity
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData.SetActivePage(StoreNavPages.Tokens, "Access Tokens", Context.GetStoreData().Id);
}

<h3 class="mb-4">@ViewData["Title"]</h3>

<div class="row">
    <div class="col-md-8">
        <h5>Token Information</h5>
        <table class="table table-hover">
            <tr>
                <th>Label</th>
                <td>@Model.Label</td>
            </tr>
            <tr>
                <th>SIN</th>
                <td>@Model.SIN</td>
            </tr>
            <tr>
                <th>Token</th>
                <td>@Model.Value</td>
            </tr>
        </table>
    </div>
</div>