BTCPayServer/Controllers/UIHomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Abstractions.Contracts;
using BTCPayServer.Client;
using BTCPayServer.Components.StoreSelector;
using BTCPayServer.Data;
using BTCPayServer.Filters;
using BTCPayServer.HostedServices;
using BTCPayServer.Models;
using BTCPayServer.Models.StoreViewModels;
using BTCPayServer.Payments;
using BTCPayServer.Payments.Lightning;
using BTCPayServer.Security;
using BTCPayServer.Services;
using BTCPayServer.Services.Apps;
using BTCPayServer.Services.Stores;
using ExchangeSharp;
using Google.Apis.Auth.OAuth2;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using NBitcoin;
using NBitcoin.Payment;
using NBitpayClient;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace BTCPayServer.Controllers
{
    public class UIHomeController : Controller
    {
        private readonly ISettingsRepository _settingsRepository;
        private readonly StoreRepository _storeRepository;
        private readonly IFileProvider _fileProvider;
        private readonly BTCPayNetworkProvider _networkProvider;
        private IHttpClientFactory HttpClientFactory { get; }
        private SignInManager<ApplicationUser> SignInManager { get; }
        public LanguageService LanguageService { get; }

        public UIHomeController(IHttpClientFactory httpClientFactory,
                              ISettingsRepository settingsRepository,
                              IWebHostEnvironment webHostEnvironment,
                              LanguageService languageService,
                              StoreRepository storeRepository,
                              BTCPayNetworkProvider networkProvider,
                              SignInManager<ApplicationUser> signInManager)
        {
            _settingsRepository = settingsRepository;
            HttpClientFactory = httpClientFactory;
            LanguageService = languageService;
            _networkProvider = networkProvider;
            _storeRepository = storeRepository;
            _fileProvider = webHostEnvironment.WebRootFileProvider;
            SignInManager = signInManager;
        }

        [HttpGet("home")]
        public Task<IActionResult> Home()
        {
            return Index();
        }

        [Route("")]
        [DomainMappingConstraint]
        public async Task<IActionResult> Index()
        {
            if ((await _settingsRepository.GetTheme()).FirstRun)
            {
                return RedirectToAction(nameof(UIAccountController.Register), "UIAccount");
            }

            if (SignInManager.IsSignedIn(User))
            {
                var userId = SignInManager.UserManager.GetUserId(HttpContext.User);
                var storeId = HttpContext.GetUserPrefsCookie()?.CurrentStoreId;
                if (storeId != null)
                {
                    // verify store exists and redirect to it
                    var store = await _storeRepository.FindStore(storeId, userId);
                    if (store != null)
                    {
                        return RedirectToStore(store);
                    }
                }
                
                var stores = await _storeRepository.GetStoresByUserId(userId);
                if (stores.Any())
                {
                    // redirect to first store
                    return RedirectToStore(stores.First());
                }
                
                var vm = new HomeViewModel
                {
                    HasStore = stores.Any()
                };
                
                return View("Home", vm);
            }

            return Challenge();
        }

        [Route("misc/lang")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie + "," + AuthenticationSchemes.Greenfield)]
        public IActionResult Languages()
        {
            return Json(LanguageService.GetLanguages(), new JsonSerializerSettings { Formatting = Formatting.Indented });
        }

        [Route("misc/permissions")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie + "," + AuthenticationSchemes.Greenfield)]
        public IActionResult Permissions()
        {
            return Json(Client.Models.PermissionMetadata.PermissionNodes, new JsonSerializerSettings { Formatting = Formatting.Indented });
        }

        [Route("swagger/v1/swagger.json")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie + "," + AuthenticationSchemes.Greenfield)]
        public async Task<IActionResult> Swagger()
        {
            JObject json = new JObject();
            var directoryContents = _fileProvider.GetDirectoryContents("swagger/v1");
            foreach (IFileInfo fi in directoryContents)
            {
                await using var stream = fi.CreateReadStream();
                using var reader = new StreamReader(fi.CreateReadStream());
                json.Merge(JObject.Parse(await reader.ReadToEndAsync()));
            }
            var servers = new JArray();
            servers.Add(new JObject(new JProperty("url", HttpContext.Request.GetAbsoluteRoot())));
            json["servers"] = servers;
            return Json(json);
        }

        [Route("docs")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie)]
        public IActionResult SwaggerDocs()
        {
            return View();
        }

        [Route("recovery-seed-backup")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanModifyStoreSettings)]
        public IActionResult RecoverySeedBackup(RecoverySeedBackupViewModel vm)
        {
            return View("RecoverySeedBackup", vm);
        }

        [HttpPost]
        [Route("postredirect-callback-test")]
        public ActionResult PostRedirectCallbackTestpage(IFormCollection data)
        {
            var list = data.Keys.Aggregate(new Dictionary<string, string>(), (res, key) =>
            {
                res.Add(key, data[key]);
                return res;
            });
            return Json(list);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public RedirectToActionResult RedirectToStore(StoreData store)
        {
            return store.Role == StoreRoles.Owner 
                ? RedirectToAction("Dashboard", "UIStores", new { storeId = store.Id }) 
                : RedirectToAction("ListInvoices", "UIInvoice", new { storeId = store.Id });
        }
    }
}

BTCPayServer/Views/Shared/CameraScanner.cshtml
@inject BTCPayServer.Security.ContentSecurityPolicies csp
@{
    csp.Add("worker-src", "blob:");
}

<template id="camera-qr-scanner-wrap">
	<div v-if="modalId" :id="modalId" class="modal fade" data-bs-backdrop="static">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
                    <h5 class="modal-title">
                        {{title}}
                        <span v-if="workload.length > 0">Animated QR detected: {{workload.length}} / {{workload[0].total}} scanned</span>
                        <span v-if="decoder">Animated QR detected: {{decoder.processedPartsCount()}} / {{decoder.expectedPartCount()}} scanned</span>
                    </h5>
                    <button type="button" class="btn-close" aria-label="Close" v-on:click="close">
                        <vc:icon symbol="close"/>
                    </button>
				</div>
				<div class="modal-body">
					<slot/>
				</div>
			</div>
		</div>
	</div>
	<div v-else>
		<slot></slot>
		<div v-if="workload.length > 0">Animated QR detected: {{workload.length}} / {{workload[0].total}} scanned</div>
	</div>
</template>

<div id="camera-qr-scanner-modal-app" v-cloak class="only-for-js">
    <scanner-wrap v-bind="$data" v-on:close="close">
        <div  class="d-flex justify-content-center align-items-center" :class="{'border border-secondary': !isModal}">
            <div class="spinner-border text-secondary position-absolute" role="status"></div>
            <qrcode-drop-zone v-on:decode="onDecode" v-on:init="logErrors">
                <qrcode-stream v-on:decode="onDecode" v-on:init="onInit" :camera="cameraOff? 'off': cameras[camera]" :device-id="cameras[camera]" :track="paint"/>
            </qrcode-drop-zone>
            <qrcode-capture v-if="noStreamApiSupport" v-on:decode="onDecode" :camera="cameraOff? 'off': cameras[camera]" :device-id="cameras[camera]"/>
            
        </div>
        <div v-if="isLoaded && requestInput && cameras.length > 2" class="d-flex justify-content-center align-items-center mt-3">
            <button class="btn btn-secondary text-center" v-on:click="nextCamera">Switch camera</button>
        </div>
        <div v-else-if="qrData || errorMessage">
            <div v-if="errorMessage" class="alert alert-danger" role="alert">
                {{errorMessage}}
            </div>
            <div v-if="qrData" class="font-monospace mt-3" style="overflow:hidden;text-overflow:ellipsis;">
                {{qrData}}
            </div>
            <div class="mt-3">
                <button type="button" class="btn btn-primary me-1" v-if="qrData" v-on:click="submitData">Submit</button>
                <button type="button" class="btn btn-secondary me-1" v-on:click="retry">Retry</button>
                <button type="button" class="btn btn-outline-secondary" v-if="isModal" v-on:click="close">Cancel</button>
            </div>
        </div>
    </scanner-wrap>
</div>

<script>
function initCameraScanningApp(title, onDataSubmit, modalId, submitOnScan = false) {
	const isModal = !!modalId;

	Vue.component('scanner-wrap', {
		props: ["modalId", "title", "workload", "decoder"],
		template: "#camera-qr-scanner-wrap",
		methods: {
			close() {
				this.$emit('close');
			}
		}
  	});

    const app = new Vue({
		el: '#camera-qr-scanner-modal-app',
		data() {
			return {
				isModal,
				isLoaded: !isModal,
				title: title,
				modalId: modalId,
				noStreamApiSupport: false,
				qrData: null,
				errorMessage: null,
				workload: [],
				camera: 0,
				cameraOff: true,
				cameras: ["auto"],
				decoder: null,
				submitOnScan
			}
		},
		mounted() {
			if (this.isModal) {
				const modal = document.getElementById(this.modalId);
				modal.addEventListener('shown.bs.modal', () => { this.isLoaded = true; this.cameraOff = false; });
				modal.addEventListener('hide.bs.modal', () => { this.isLoaded = false; this.cameraOff = true; });
			} else {
				this.isLoaded = true;
				this.cameraOff = false;
			}
		},
		computed: {
			requestInput() {
				return !this.cameraOff && this.errorMessage === null;
			}
		},
		methods: {
		    nextCamera: function (){
		        if (this.camera === 0){
		            this.camera++;
		        } else if (this.camera == this.cameras.length -1) {
		            this.camera = 0;
		        } else {
		            this.camera++;
		        }
		    },
			setQrData (qrData) {
				this.qrData = qrData;
				this.cameraOff = !!qrData;
                if (this.qrData && this.submitOnScan) {
                    this.submitData();
                }
			},
			retry() {
				this.cameraOff = true;
				this.$nextTick(this.reset);
			},
			reset() {
				this.setQrData(null);
				this.errorMessage = null;
				this.workload = [];
                this.decoder = null;
			},
			close() {
				if (this.modalId) {
					const modal = bootstrap.Modal.getInstance(document.getElementById(this.modalId));
					modal.hide();
				}
				this.reset();
			},
			onDecode(content) {
				if (this.qrData) return;

				if (!content.toLowerCase().startsWith("ur:")) {
					this.setQrData(content);
					this.workload = [];
				} else {
                    if (this.workload.length == 0){
                        const d = this.decoder || new window.URlib.URRegistryDecoder();
                        if (d.receivePart(content)){
                            this.decoder = d;
                            if (d.isComplete()){
                                if (!this.decoder.isSuccess()){
				                    this.errorMessage = this.decoder.resultError();
                                }else{
                                    this.setQrData(this.decoder.resultRegistryType().toString());
                                }
                            }
                        }
                        if (this.decoder != null){
                            return;
                        }
                    }
					const [index, total] = window.bcur.extractSingleWorkload(content);
					if (this.workload.length > 0) {
						const currentTotal = this.workload[0].total;
						if (total !== currentTotal) {
							this.workload = [];
						}
					}
					if (!this.workload.find(i => i.index === index)) {
						this.workload.push({
							index,
							total,
							data: content,
						});
						if (this.workload.length === total) {
							const decoded = window.bcur.decodeUR(this.workload.map(i => i.data));
							this.setQrData(decoded);
						}
					}
				}
			},
			submitData() {
				if (onDataSubmit) {
					onDataSubmit(this.qrData);
				}
				this.close();
			},
			logErrors(promise) {
				promise.catch(console.error)
			},
			paint(detectedCodes, ctx) {
				for (const detectedCode of detectedCodes) {
                    const [ firstPoint, ...otherPoints ] = detectedCode.cornerPoints
                    ctx.strokeStyle = "#51b13e";
                    ctx.beginPath();
                    ctx.moveTo(firstPoint.x, firstPoint.y);
                    for (const { x, y } of otherPoints) {
                      ctx.lineTo(x, y);
                    }
                    ctx.lineTo(firstPoint.x, firstPoint.y);
                    ctx.closePath();
                    ctx.stroke();
                }
			},
			onInit(promise) {
				promise.then(() => {
					this.errorMessage = null;
					if (app.cameras.length === 1)
                    {
                        navigator.mediaDevices.enumerateDevices().then(function (devices) {
                            for (const device of devices) {
                                if (device.kind == "videoinput"){
                                   app.cameras.push( device.deviceId)
                                }
                            }
                        });
                    }					 
				}).catch(error => {
					if (error.name === 'StreamApiNotSupportedError') {
						this.noStreamApiSupport = true;
					} else if (error.name === 'NotAllowedError') {
						this.errorMessage = 'A permission to the camera is needed to scan the QR code. Please grant the browser access and then retry.'
					} else if (error.name === 'NotFoundError') {
						this.errorMessage = 'A camera was not detected on your device.'
					} else if (error.name === 'NotSupportedError') {
						this.errorMessage = 'This page is served in non-secure context (HTTPS, localhost or file://)'
					} else if (error.name === 'NotReadableError') {
						this.errorMessage = 'Couldn\'t access your camera. Is it already in use?'
					} else if (error.name === 'OverconstrainedError') {
						this.errorMessage = 'Constraints don\'t match any installed camera.'
					} else {
						this.errorMessage = 'UNKNOWN ERROR: ' + error.message
					}
				})
			}
		}
	});
}
</script>

BTCPayServer/Views/Shared/Confirm.cshtml
@model ConfirmModel

@{
    ViewData["Title"] = Model.Title;
    Layout = "_LayoutSimple";
}

@section PageHeadContent {
    <style>
        body > .content-wrapper { display: flex; min-height: 100vh; }
        .modal-dialog .btn-close { display: none; }
    </style>
}

@section PageFootContent {
    <script>
        document.getElementById('ConfirmCancel').addEventListener('click', function () {
            history.back();
            return false;
        })
    </script>
}

<partial name="ConfirmModal" model="Model" />

BTCPayServer/Views/Shared/EmailsBody.cshtml
@model BTCPayServer.Models.ServerViewModels.EmailsViewModel

<div class="row">
    <div class="col-xl-8 col-xxl-constrain">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h3 class="mb-0">@ViewData["Title"]</h3>
            <div class="dropdown only-for-js" id="quick-fill">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="QuickFillDropdownToggle">
                    Quick Fill
                </button>
                <div class="dropdown-menu" aria-labelledby="QuickFillDropdownToggle">
                    <a class="dropdown-item" href="" data-server="smtp.gmail.com" data-port="587">Gmail.com</a>
                    <a class="dropdown-item" href="" data-server="mail.yahoo.com" data-port="587">Yahoo.com</a>
                    <a class="dropdown-item" href="" data-server="smtp.mailgun.org" data-port="587">Mailgun</a>
                    <a class="dropdown-item" href="" data-server="smtp.office365.com" data-port="587">Office365</a>
                    <a class="dropdown-item" href="" data-server="smtp.sendgrid.net" data-port="587">SendGrid</a>
                </div>
            </div>
        </div>
    </div>
</div>

<form method="post" autocomplete="off">
    <div class="row">
        <div class="col-xl-8 col-xxl-constrain">
            @if (!ViewContext.ModelState.IsValid)
            {
                <div asp-validation-summary="All" class="text-danger"></div>
            }
            <div class="form-group">
                <label asp-for="Settings.Server" class="form-label"></label>
                <input asp-for="Settings.Server" data-fill="server" class="form-control"/>
                <span asp-validation-for="Settings.Server" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.Port" class="form-label"></label>
                <input asp-for="Settings.Port" data-fill="port" class="form-control"/>
                <span asp-validation-for="Settings.Port" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.FromDisplay" class="form-label"></label>
                <input asp-for="Settings.FromDisplay" class="form-control"/>
                <small class="form-text text-muted">
                    Some email providers (like Gmail) don't allow you to set your display name, so this setting may not have any effect.
                </small>
                <span asp-validation-for="Settings.FromDisplay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.From" class="form-label"></label>
                <input asp-for="Settings.From" class="form-control"/>
                <span asp-validation-for="Settings.From" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.Login" class="form-label"></label>
                <input asp-for="Settings.Login" class="form-control"/>
                <small class="form-text text-muted">
                    For many email providers (like Gmail) your login is your email address.
                </small>
                <span asp-validation-for="Settings.Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                @if (!Model.PasswordSet)
                {

                    <label asp-for="Settings.Password" class="form-label"></label>
                    <input asp-for="Settings.Password" type="password" class="form-control"/>
                    <span asp-validation-for="Settings.Password" class="text-danger"></span>
                }
                else
                {
                    <label asp-for="Settings.Password" class="form-label"></label>
                    <div class="input-group">
                        <input value="Configured" type="text" readonly class="form-control"/>
                        <button type="submit" class="btn btn-danger" name="command" value="ResetPassword" id="ResetPassword">Reset</button>
                    </div>
                }
            </div>
            <input asp-for="PasswordSet" type="hidden"/>
            <button type="submit" class="btn btn-primary mt-2" name="command" value="Save" id="Save">Save</button>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-8 col-xxl-constrain">
            <div class="form-group">
                <h3 class="mt-5 mb-3">Testing</h3>
                <p>
                    To test your settings, enter an email address below.
                </p>
                <label asp-for="TestEmail" class="form-label"></label>
                <input asp-for="TestEmail" class="form-control" />
                <span asp-validation-for="TestEmail" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-secondary mt-2" name="command" value="Test" id="Test">Send Test Email</button>
        </div>
    </div>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        delegate('click', '#quick-fill .dropdown-menu a', function (e) {
            e.preventDefault();
            
            const data = e.target.dataset;
            Object.keys(data).forEach(function (key) {
                const value = data[key];
                const input = document.querySelector('input[data-fill="' + key + '"]');
                if (input) {
                    const type = input.getAttribute('type');
                    if (type === 'checkbox') {
                        input.checked = value;
                    } else {
                        input.value = value;
                    }
                }
            });
        });
    });
</script>

BTCPayServer/Views/Shared/LayoutFoot.cshtml
@addTagHelper *, BundlerMinifier.TagHelpers

<bundle name="wwwroot/bundles/bootstrap-bundle.min.js" asp-append-version="true" />
<bundle name="wwwroot/bundles/main-bundle.min.js" asp-append-version="true" />

BTCPayServer/Views/Shared/NotificationEmailWarning.cshtml
<div class="alert alert-warning alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        <vc:icon symbol="close" />
    </button>
    The Email settings have not been configured on this server or store yet. Setting this field will not send emails until then. <a asp-action="Emails" asp-controller="UIStores" asp-route-storeId="@Model" class="alert-link">Configure store email settings</a>
</div>

BTCPayServer/Views/Shared/ShowQR.cshtml
<div id="scan-qr-modal-app">
    <div class="modal" tabindex="-1" role="dialog" :id="modalId">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{title}} <template v-if="fragments.length > 1">({{index+1}}/{{fragments.length}})</template></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <vc:icon symbol="close"/>
                    </button>
                </div>
                <div class="modal-body ">
                    <div class="qr-container text-center mt-3" style="min-height: 256px;">
                        <qrcode v-bind:value="currentFragment" :options="{ width: 256,height:256, margin: 1, color: {dark:'#000', light:'#f5f5f7'} }">
                        </qrcode>
                    </div>
                    <ul class="nav justify-content-center mt-4 mb-3" v-if="allowedModes.length > 1">
                        <li class="nav-item" v-for="allowedMode in allowedModes">
                            <a class="btcpay-pill"
                               v-bind:class="{ 'active': allowedMode == currentMode}" href="#" v-on:click="currentMode = allowedMode">
                                {{allowedMode}}
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
 function initQRShow(title, data, modalId)
 {
 	return new Vue(
 	{
 		el: '#scan-qr-modal-app',
 		components:
 		{
 			qrcode: VueQrcode
 		},
 		data:
 		{
 			index: -1,
 			title: title,
 			speed: 500,
 			data: data,
 			fragments: [],
 			active: false,
 			modalId: modalId,
 			currentMode: "bcur",
 			allowedModes: ["static","bcur"]
 		},
 		computed:
 		{
 			currentFragment: function ()
 			{
 				return this.fragments[this.index];
 			}
 		},
 		mounted: function ()
 		{
 			var self = this;
 			$("#" + this.modalId)
 				.on("shown.bs.modal", function ()
 				{
 					self.start();
 				})
 				.on("hide.bs.modal", function ()
 				{
 					self.active = false;
 				});
 			self.setFragments();
 		},
 		watch:
 		{
 		    currentMode: function(){
 				this.setFragments();
 		    },
 			data: function ()
 			{
 				this.setFragments();
 			}
 		},
 		methods:
 		{
 			setFragments: function ()
 			{
 				if (!this.data)
 				{
 					this.fragments = [];
 					return;
 				}
 				if (this.currentMode == "bcur"){
 				    this.fragments = window.bcur.encodeUR(this.data.toString(), 200);
 				}else{
 				    this.fragments = [this.data.toString()];
 				}
 			},
 			start: function ()
 			{
 				this.active = true;
 				this.index = -1;
 				this.playNext();
 			},
 			playNext: function ()
 			{
 				if (!this.active)
 				{
 					return;
 				}
 				this.index++;
 				if (this.index > (this.fragments.length - 1))
 				{
 					this.index = 0;
 				}
 				setTimeout(this.playNext, this.speed)
 			}
 		}
 	});
 }
 </script>

BTCPayServer/Views/Shared/VaultElements.cshtml
<script id="VaultConnection" type="text/template">
    <div class="vault-feedback vault-feedback1 mb-2 d-flex">
        <span class="vault-feedback-icon mt-1 me-2"></span> <span class="vault-feedback-content flex-1"></span>
    </div>
    <div class="vault-feedback vault-feedback2 mb-2 d-flex">
        <span class="vault-feedback-icon mt-1 me-2"></span> <span class="vault-feedback-content flex-1"></span>
    </div>
    <div class="vault-feedback vault-feedback3 mb-2 d-flex">
        <span class="vault-feedback-icon mt-1 me-2"></span> <span class="vault-feedback-content flex-1"></span>
    </div>
    <div id="pin-input" class="mt-4" style="display: none;">
        <div class="row">
            <div class="col">
                <div class="input-group mb-2">
                    <input id="pin-display" type="text" class="form-control" readonly>
                    <div id="pin-display-delete" class="input-group-text cursor-pointer"><span class="fa fa-remove"></span></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col"><div class="pin-button" id="pin-7"></div></div>
            <div class="col"><div class="pin-button" id="pin-8"></div></div>
            <div class="col"><div class="pin-button" id="pin-9"></div></div>
        </div>
        <div class="row">
            <div class="col"><div class="pin-button" id="pin-4"></div></div>
            <div class="col"><div class="pin-button" id="pin-5"></div></div>
            <div class="col"><div class="pin-button" id="pin-6"></div></div>
        </div>
        <div class="row">
            <div class="col"><div class="pin-button" id="pin-1"></div></div>
            <div class="col"><div class="pin-button" id="pin-2"></div></div>
            <div class="col"><div class="pin-button" id="pin-3"></div></div>
        </div>
    </div>
    <div id="passphrase-input" class="mt-4" style="display: none;">
        <div class="form-group">
            <label for="Password" class="input-group-text"><span class="input-group-addon fa fa-lock"></span></label>
            <input id="Password" type="password" class="form-control" placeholder="Passphrase" />
        </div>
        <div class="form-group">
            <div class="input-group">
                <label for="PasswordConfirmation" class="input-group-text"><span class="input-group-addon fa fa-lock"></span></label>
                <input id="PasswordConfirmation" type="password" class="form-control" placeholder="Passphrase confirmation" />
            </div>
        </div>
    </div>
</script>

BTCPayServer/Views/Shared/_LayoutSignedOut.cshtml
@{
    Layout = "_LayoutSimple";
    ViewBag.ShowLeadText ??= false;
}

@section PageHeadContent {
    <style>
        .account-form {
            max-width: 35em;
            margin: 0 auto var(--btcpay-space-xl);
            padding: 2rem;
            background: var(--btcpay-bg-tile);
            border-radius: var(--btcpay-border-radius);
        }
        
        .account-form h4 {
            margin-bottom: 1.5rem;
        }
    </style>
    @await RenderSectionAsync("PageHeadContent", false)
}

@section PageFootContent {
    <partial name="_ValidationScriptsPartial" />
    @await RenderSectionAsync("PageFootContent", false)
}

<div class="row justify-content-center mb-2">
    <div class="col text-center">
        <a asp-controller="UIHome" asp-action="Index" tabindex="-1">
            <img src="~/img/btcpay-logo.svg" alt="BTCPay Server" class="mb-4" height="70" asp-append-version="true"/>
        </a>

        <h1 class="h2 mb-3">Welcome to your BTCPay&nbsp;Server</h1>
        @if (ViewBag.ShowLeadText)
        {
            <p class="lead">
                <span class="d-sm-block">A self-hosted, open-source cryptocurrency payment processor.</span>
                <span class="d-sm-block">It is secure, private, censorship-resistant and free.</span>
            </p>
        }

        <partial name="_StatusMessage"/>
    </div>
</div>

<div class="account-form">
    <h4>@ViewData["Title"]</h4>
    @RenderBody()
</div>

<div class="row justify-content-center mt-5">
    <div class="col">
        <partial name="_BTCPaySupporters"/>
    </div>
</div>

BTCPayServer/Views/Shared/_LayoutWizard.cshtml
@{
    Layout = "_LayoutSimple";
}

@section PageHeadContent {
    <link href="~/main/wizard.css" rel="stylesheet" asp-append-version="true" />
    @await RenderSectionAsync("PageHeadContent", false)
}

@section PageFootContent {
    @await RenderSectionAsync("PageFootContent", false)
}

<nav id="wizard-navbar">
    @await RenderSectionAsync("Navbar", false)
</nav>

<div class="row justify-content-md-center mt-5 pt-sm-3 pt-md-0">
    <main class="col-md-10 col-lg-8 col-xl-7">
        <partial name="_StatusMessage" />
        @RenderBody()
    </main>
</div>